language: c
before_install:
  - PROJECT_PATH=~/victorhaggqvist/pebble-battery-monitor
  - PEBBLE_SDK=PebbleSDK-2.2
  - echo 'Installing Pebble SDK Dependencies...'
  - echo 'SDK ${PEBBLE_SDK}'
  - cd ~ 

# Get the Pebble SDK and toolchain
  - wget http://dump.victorhaggqvist.com/${PEBBLE_SDK}.tar.gz -O PebbleSDK.tar.gz #cuz need to login to download from pebble..
  - wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk/arm-cs-tools-ubuntu-universal.tar.gz

# Build the Pebble directory
  - mkdir ~/pebble-dev
  - cd ~/pebble-dev
  
# Extract the SDK
  - tar -zxf ~/PebbleSDK.tar.gz
  - cd ~/pebble-dev/${PEBBLE_SDK}

# Extract the toolchain
  - tar -zxf ~/arm-cs-tools-ubuntu-universal.tar.gz
  - export PATH=~/pebble-dev/${PEBBLE_SDK}/bin:$PATH

script:
  - echo "Building Pebble project..."
  - cd ${PROJECT_PATH}
  - pebble build

